spring:
  jpa:
   generate-ddl: true
   hibernate:
     ddl-auto: create
     properties:
       dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    initialize: true
    url: jdbc:mysql://localhost/buccidb2?useSSL=false
    username: root
    password: hey
    driver: com.mysql.jdbc.Driver
    separator: ^;
  profiles:
    include: constants
    active: constants

logging:
  level:
    org:
      hibernate:
        SQL: debug
    
settings:
  caching:
    popularityCache:
      delay_ms: 100000      
      
      
      
      
      
