constants:  

  artist_not_found_msg: "Could not find artist."
  concert_not_found_msg: "Could not find concert."
  album_not_found_msg: "Could not find album."
  song_not_found_msg: "Could not find song."
  resource_not_found_msg: "Could not find resource."

  general_access_denied_msg: "Access denied"
  admin_access_denied_msg: "Access denied, need role of Admin for this resource."
  artist_access_denied_msg: "Access denied, need role of Artist for this resource."

  duration_error_msg: "Duration needed."
  ownership_error_msg: "You do not own this resource."
  storage_error_msg: "An error occured while storing this resource."

  successful_addition_msg: "Adding the item was successful."  
  successful_charge_msg: "Charging the user(s) was successful."
  successful_request_msg: "Request creation was successful."
  successful_deletion_msg: "Deletion was successful."

  not_logged_in_msg: "Not Logged In" 
  logged_in_msg: "Already Logged In"
  already_artist: "You are already an artist"

  start: 0
  
  new_releases_limit: 10
  top_albums_limit: 10
  top_songs_limit: 10
  top_playlists_limit: 10
  
  royalty_price: 0.03
  moonman_tier_monthly_price: 30
  trex_tier_monthly_price: 45
  nitrodubs_tier_monthly_price: 100
  
  moonman_max: 4
  trex_max: 9
  nitrodubs_max: 17 
    
  weeks_ago: 7
  two_weeks_ago: 14
  all_time: CURDATE()
    
  song_count: stats.song_count
  play_count: numPlays
    

  session: user
  
  signup_premium_price: 4.99
  monthly_premium_price: 4.99


email:

  siteURL: "http://localhost:4200"


  resetEmailSubject: "BucciTunes reset email confirmation"
  resetEmailText: "Follow the link to reset your email: %s"
    
  ApprovedArtistSubject: "You are now a BucciTunes Artist!"
  ApprovedArtistText: "Congratulations, you are now an artist. You can now visit www.buccitunes.com/artist/%s to see your artist page. Make sure you edit your billing information to receive payments."
  
  DeniedArtistSubject: "About Your Artist Request"
  DeniedArtistText: "Sorry %s, your request to become an artist was denied"
    
  ApprovedAlbumSubject: "BucciTunes Album Approval"
  ApprovedAlbumText: "Your album: %s has been approved and is now posted."
  
  ApprovedSongSubject: "BucciTunes Song Approval"
  ApprovedSongText: "Your song: %s has been denied."
  
  DeniedAlbumSubject: "BucciTunes Album Denied"
  DeniedAlbumText: "Your album: %s has been approved and is now posted."  
    
  DeniedSongSubject: "BucciTunes Album Denial"
  DeniedSongText: "Your Song: %s has been denied."    

  ApprovedConcertSubject: "BucciTunes Concert Approved"
  ApprovedConcertText: "Your concert: %s has been approved and is not posted."
  
  DeniedConcertSubject: "BucciTunes Concert Denied"
  DeniedConcertText: "BucciTunes Concert Denied Confirmation."
  
  AccountConfirmationSubject: "BucciTunes Account Creation Confirmation"
  AccountConfirmationText: "An account has been created for you at www.buccitunes.com/user/%s."
  

    