spring:
  jpa:
   generate-ddl: true
   hibernate:
     ddl-auto: create
     properties:
       dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    initialize: true
    url: jdbc:mysql://localhost/buccidb2?useSSL=false
    username: root
    password: trees10
    driver: com.mysql.jdbc.Driver
    separator: ^;

  profiles:
    include: constants
    active: constants

  mail:
    host: smtp.gmail.com
    port: 465
    username: buccitunes.com
    password: alrightrobby
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false



logging:
  level:
    org:
      hibernate:
        SQL: debug
    
settings:
  caching:
    popularityCache:
      delay_ms: 100000
  filesystem:
    location: user.home  
      

      
      
      
