constants:  
  start: 0
  
  new_releases_limit: 10
  top_albums_limit: 10
  top_songs_limit: 10
  top_playlists_limit: 10
  
  royalty_price: 0.03
  moonman_tier_monthly_price: 30
  trex_tier_monthly_price: 45
  nitrodubs_tier_monthly_price: 100
  
  moonman_max: 4
  trex_max: 9
  nitrodubs_max: 17 
    
  weeks_ago: 7
  two_weeks_ago: 14
  all_time: CURDATE()
    
  song_count: stats.song_count
  play_count: numPlays
    
  not_logged_in: Not Logged In 
  logged_in: Already Logged In
  session: user
  
  signup_premium_price: 5.00
  monthly_premium_price: 5.00


email:
  ApprovedAlbumSubject: "BucciTunes Album Approval"
  ApprovedAlbumText: "Your album: %s has been approved and is now posted."
  
  ApprovedSongSubject: "BucciTunes Song Approval"
  ApprovedSongText: "Your song: %s has been denied."
  
  DeniedAlbumSubject: "BucciTunes Album Denied"
  DeniedAlbumText: "Your album: %s has been approved and is now posted."  
    
  DeniedSongSubject: "BucciTunes Album Denial"
  DeniedSongText: "Your Song: %s has been denied."    

  ApprovedConcertSubject: "BucciTunes Concert Approved"
  ApprovedConcertText: "Your concert: %s has been approved and is not posted."
  
  DeniedConcertSubject: "BucciTunes Concert Denied"
  DeniedConcertText: "BucciTunes Concert Denied Confirmation."
  
  AccountConfirmationSubject: "BucciTunes Account Creation Confirmation"
  AccountConfirmationText: "An account has been created for you at www.buccitunes.com/user/%s."
  

    