package com.buccitunes.constants;

public enum Genre {
	
	HIPHOP, COUNTRY, POP, LATIN, SLAV, BLOCK, RNB, METAL, PROGRESSIVE_METAL, FUNK, ROCK, ELECTRONIC, JAZZ, PUNK, INDIE, RUSSIAN_OPERA, OPERA
	, WEEB, UK_RAP
}
